// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopNongSan.Models;

#nullable disable

namespace ShopNongSan.Migrations
{
    [DbContext(typeof(NongSanContext))]
    [Migration("20250902055302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopNongSan.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC071F8DDA0E");

                    b.HasIndex(new[] { "Ten" }, "UQ__DanhMuc__C451FA83ABD54D82")
                        .IsUnique();

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.DoiTra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DonHangId")
                        .HasColumnType("bigint");

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DoiTra__3214EC0763F492C6");

                    b.HasIndex("DonHangId");

                    b.ToTable("DoiTra", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.DoiTraChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DoiTraId")
                        .HasColumnType("bigint");

                    b.Property<long>("DonHangChiTietId")
                        .HasColumnType("bigint");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DoiTraCh__3214EC07C55DFF0E");

                    b.HasIndex("DoiTraId");

                    b.HasIndex("DonHangChiTietId");

                    b.ToTable("DoiTraChiTiet", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DonHang__3214EC07D658CA63");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex(new[] { "MaDonHang" }, "UQ__DonHang__129584ACA72906BD")
                        .IsUnique();

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHangChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("DonHangId")
                        .HasColumnType("bigint");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DonHangC__3214EC07FBC5BB09");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("DonHangChiTiet", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.GioHang", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.GioHangChiTiet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("GioHangId")
                        .HasColumnType("bigint");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GioHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("GioHangChiTiet", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ThuongHieuId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SanPham__3214EC0729DF377F");

                    b.HasIndex("ThuongHieuId");

                    b.HasIndex(new[] { "DanhMucId", "ThuongHieuId", "Gia" }, "IX_SanPham_Loc");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__TaiKhoan__3214EC07D60341CD");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0B46025BB")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.ThongTinNguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TaiKhoanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__ThongTin__3214EC07DC8EDCDB");

                    b.HasIndex(new[] { "TaiKhoanId" }, "UQ__ThongTin__9A124B4426867C18")
                        .IsUnique();

                    b.ToTable("ThongTinNguoiDung", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ThuongHi__3214EC07A075CB8D");

                    b.HasIndex(new[] { "Ten" }, "UQ__ThuongHi__C451FA831A884426")
                        .IsUnique();

                    b.ToTable("ThuongHieu", (string)null);
                });

            modelBuilder.Entity("ShopNongSan.Models.DoiTra", b =>
                {
                    b.HasOne("ShopNongSan.Models.DonHang", "DonHang")
                        .WithMany("DoiTras")
                        .HasForeignKey("DonHangId")
                        .IsRequired()
                        .HasConstraintName("FK_DoiTra_DonHang");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("ShopNongSan.Models.DoiTraChiTiet", b =>
                {
                    b.HasOne("ShopNongSan.Models.DoiTra", "DoiTra")
                        .WithMany("DoiTraChiTiets")
                        .HasForeignKey("DoiTraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DRTCT_DoiTra");

                    b.HasOne("ShopNongSan.Models.DonHangChiTiet", "DonHangChiTiet")
                        .WithMany("DoiTraChiTiets")
                        .HasForeignKey("DonHangChiTietId")
                        .IsRequired()
                        .HasConstraintName("FK_DRTCT_DHCT");

                    b.Navigation("DoiTra");

                    b.Navigation("DonHangChiTiet");
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHang", b =>
                {
                    b.HasOne("ShopNongSan.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("TaiKhoanId")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_TaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHangChiTiet", b =>
                {
                    b.HasOne("ShopNongSan.Models.DonHang", "DonHang")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DHCT_DonHang");

                    b.HasOne("ShopNongSan.Models.SanPham", "SanPham")
                        .WithMany("DonHangChiTiets")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK_DHCT_SanPham");

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopNongSan.Models.GioHang", b =>
                {
                    b.HasOne("ShopNongSan.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("GioHangs")
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_TaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopNongSan.Models.GioHangChiTiet", b =>
                {
                    b.HasOne("ShopNongSan.Models.GioHang", "GioHang")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("GioHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GHCT_GioHang");

                    b.HasOne("ShopNongSan.Models.SanPham", "SanPham")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK_GHCT_SanPham");

                    b.Navigation("GioHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ShopNongSan.Models.SanPham", b =>
                {
                    b.HasOne("ShopNongSan.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_DanhMuc");

                    b.HasOne("ShopNongSan.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuId")
                        .HasConstraintName("FK_SanPham_ThuongHieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("ShopNongSan.Models.ThongTinNguoiDung", b =>
                {
                    b.HasOne("ShopNongSan.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("ThongTinNguoiDung")
                        .HasForeignKey("ShopNongSan.Models.ThongTinNguoiDung", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TTND_TaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("ShopNongSan.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ShopNongSan.Models.DoiTra", b =>
                {
                    b.Navigation("DoiTraChiTiets");
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHang", b =>
                {
                    b.Navigation("DoiTras");

                    b.Navigation("DonHangChiTiets");
                });

            modelBuilder.Entity("ShopNongSan.Models.DonHangChiTiet", b =>
                {
                    b.Navigation("DoiTraChiTiets");
                });

            modelBuilder.Entity("ShopNongSan.Models.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("ShopNongSan.Models.SanPham", b =>
                {
                    b.Navigation("DonHangChiTiets");

                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("ShopNongSan.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("ThongTinNguoiDung");
                });

            modelBuilder.Entity("ShopNongSan.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
